spring:
  application:
    name: ${project.build.finalName}
  boot:
    admin:
      client:
        url: http://localhost:8090
      #ui:
        #brand: swesource
  cloud:
    config:
      server:
        git:
          uri: https://github.com/swesource/spring-cloud-configs
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  address: localhost
  port: 8092
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
management:
  #  address: 127.0.0.1
  server:
    port: 8093
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        #exclude: "*"
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS # NEVER | ALWAYS | WHEN_AUTHORIZED
    configprops:
      show-values: ALWAYS # NEVER | ALWAYS | WHEN_AUTHORIZED
    info:
      enabled: true
      show-details: always
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
